name: Linter test

on: [push]

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          make lint
                
    
